import type { AstroIntegration } from "astro";
import fs from "fs";
import matter from "gray-matter";
import path from "path";

type Options = {
  pagesDirs: string[];
  output?: string;
};

type RouteMeta = {
  title: string;
  order: number;
  sitemap: boolean;
  showInHeader: boolean;
  isStagingOnly: boolean;
};

type Route = RouteMeta & {
  path: string;
};

export function generateRoutes(options: Options): AstroIntegration {
  const { pagesDirs, output = "src/routes.generated.ts" } = options;

  return {
    name: "generate-routes",
    hooks: {
      "astro:server:setup": () => generate(pagesDirs, output),
      "astro:build:start": () => generate(pagesDirs, output),
    },
  };
}

function generate(pagesDirs: string[], outputFile: string) {
  const routes: Record<string, Route> = {};

  for (const dir of pagesDirs.map((d) => path.resolve(d))) {
    if (!fs.existsSync(dir)) continue;

    for (const file of getFiles(dir)) {
      const meta = extractMeta(file, fs.readFileSync(file, "utf-8"));
      if (!meta) continue;

      const relativePath =
        file
          .replace(dir, "")
          .replace(/\.(astro|md|mdx)$/, "")
          .replace(/\/index$/, "") || "/";

      const key =
        relativePath === "/"
          ? "home"
          : relativePath.split("/").filter(Boolean).pop();

      if (key) routes[key] = { path: relativePath, ...meta };
    }
  }

  fs.writeFileSync(path.resolve(outputFile), buildOutput(routes));
}

function getFiles(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return getFiles(full);
    return /\.(astro|md|mdx)$/.test(entry.name) ? [full] : [];
  });
}

function extractMeta(file: string, raw: string): RouteMeta | null {
  let data: Record<string, unknown>;

  if (file.endsWith(".astro")) {
    // Extract the `frontmatter = { ... }` object body from the TS frontmatter block
    // and parse it as YAML (valid after stripping trailing commas)
    const frontmatterBlock = raw.match(/^---([\s\S]*?)---/)?.[1] ?? "";
    const objBlock =
      frontmatterBlock.match(/frontmatter\s*=\s*\{([^}]*)\}/)?.[1] ?? "";
    ({ data } = matter(`---\n${objBlock.replace(/,\s*$/gm, "")}\n---`));
  } else {
    ({ data } = matter(raw));
  }

  const title = data.title as string | undefined;
  if (!title) return null;

  return {
    title,
    sitemap: data.sitemap !== false,
    order: (data.order as number | undefined) ?? 999,
    showInHeader: !!data.showInHeader,
    isStagingOnly: !!data.isStagingOnly,
  };
}

function toRouteKey(input: string): string {
  const camel = input
    .replace(/[^a-zA-Z0-9-_]/g, "")
    .split(/[-_]/)
    .filter(Boolean)
    .map((part, i) =>
      i === 0
        ? part[0].toLowerCase() + part.slice(1)
        : part[0].toUpperCase() + part.slice(1),
    )
    .join("");
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(camel) ? camel : `"${camel}"`;
}

function buildOutput(routes: Record<string, Route>) {
  const entries = Object.entries(routes)
    .sort(([, a], [, b]) => a.order - b.order || a.title.localeCompare(b.title))
    .map(
      ([key, { path, title, sitemap, order, showInHeader, isStagingOnly }]) => `
  ${toRouteKey(key)}: {
    path: buildUrl("${path}"),
    title: "${title.replace(/"/g, '\\"')}",
    sitemap: ${sitemap},
    order: ${order},
    showInHeader: ${showInHeader},
    isStagingOnly: ${isStagingOnly},
  }`,
    )
    .join(",");

  return `// ⚠️ This file is auto-generated by integrations/routeGenerator.ts — do not edit manually. ⚠️

import { isPreview } from "@/config/stage";

export const removeTrailingSlash = (path: string) =>
  path.replace(/\\/$/, "").replace(/^$/, "/");

const buildUrl = (href: string): string => {
  const baseUrl = removeTrailingSlash(import.meta.env?.BASE_URL || "");
  return isPreview ? \`\${baseUrl}\${href}\` : href;
};

export const routes = {${entries},
} as const;
`;
}
