import type { AstroIntegration } from "astro";
import matter from "gray-matter";
import fs from "node:fs";
import path from "node:path";

type Options = {
  pagesDirs: string[];
  output?: string;
};

type RouteMeta = {
  title: string;
  order: number;
  sitemap: boolean;
  showInHeader: boolean;
  isStagingOnly: boolean;
};

type Route = RouteMeta & {
  path: string;
};

export function generateRoutes(options: Options): AstroIntegration {
  const { pagesDirs, output = "src/routes.generated.ts" } = options;

  return {
    name: "generate-routes",
    hooks: {
      "astro:server:setup": () => generate(pagesDirs, output),
      "astro:build:start": () => generate(pagesDirs, output),
    },
  };
}

const SUPPORTED_EXTENSIONS = ["astro", "md", "mdx", "html"];
const SUPPORTED_EXTENSIONS_REGEXP = new RegExp(
  `\\.(${SUPPORTED_EXTENSIONS.join("|")})$`,
);

function generate(pagesDirs: string[], outputFile: string) {
  const routes: Record<string, Route> = {};

  for (const dir of pagesDirs.map((d) => path.resolve(d))) {
    if (!fs.existsSync(dir)) continue;

    for (const file of getFiles(dir)) {
      const meta = extractMeta(file, fs.readFileSync(file, "utf-8"));
      if (!meta) continue;

      const relativePath =
        file
          .replace(dir, "")
          .replace(SUPPORTED_EXTENSIONS_REGEXP, "")
          .replace(/\/index$/, "") || "/";

      const routeKey = relativePath === "/" ? "home" : toRouteKey(relativePath);

      if (routeKey) routes[routeKey] = { path: relativePath, ...meta };
    }
  }

  fs.writeFileSync(path.resolve(outputFile), buildOutput(routes));
}

function getFiles(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return getFiles(full);
    return SUPPORTED_EXTENSIONS_REGEXP.test(entry.name) ? [full] : [];
  });
}

function extractMeta(file: string, raw: string): RouteMeta | null {
  let data: Record<string, unknown>;

  if (file.endsWith(".astro")) {
    // Extract the `frontmatter = { ... }` object body from the TS frontmatter block
    // and parse it as YAML (valid after stripping trailing commas)
    const frontmatterBlock =
      new RegExp(/^---([\s\S]*?)---/).exec(raw)?.[1] ?? "";
    const objBlock =
      new RegExp(/frontmatter\s*=\s*\{([^}]*)\}/).exec(frontmatterBlock)?.[1] ??
      "";
    ({ data } = matter(`---\n${objBlock.replaceAll(/,\s*$/gm, "")}\n---`));
  } else {
    ({ data } = matter(raw));
  }

  const title = data.title as string | undefined;
  if (!title) return null;

  return {
    title,
    sitemap: data.sitemap !== false,
    order: (data.order as number | undefined) ?? 999,
    showInHeader: !!data.showInHeader,
    isStagingOnly: !!data.isStagingOnly,
  };
}

// Convert page/file identifiers into stable camelCase object keys for the route registry.
export function toRouteKey(input: string): string {
  const routeKey = input
    // Keep nested route boundaries visible in the generated key.
    .split("/")
    .filter(Boolean)
    .map((segment) =>
      segment
        .replaceAll(/[^a-zA-Z0-9-_]/g, "")
        // Normalize each path segment independently before joining nested segments with `_`.
        .split(/[-_]/)
        .filter(Boolean)
        .map((part, i) =>
          i === 0
            ? part[0].toLowerCase() + part.slice(1)
            : part[0].toUpperCase() + part.slice(1),
        )
        .join(""),
    )
    .filter(Boolean)
    .join("_");
  // Quote anything that is not a valid JS identifier so generated code stays syntactically valid.
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(routeKey)
    ? routeKey
    : `"${routeKey}"`;
}

function escapeStringLiteral(input: string): string {
  return input.replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}

function buildOutput(routes: Record<string, Route>) {
  const entries = Object.entries(routes)
    .sort(([, a], [, b]) => a.order - b.order || a.title.localeCompare(b.title))
    .map(
      ([key, { path, title, sitemap, order, showInHeader, isStagingOnly }]) => `
  ${key}: {
    path: buildUrl("${path}"),
    title: "${escapeStringLiteral(title)}",
    sitemap: ${sitemap},
    order: ${order},
    showInHeader: ${showInHeader},
    isStagingOnly: ${isStagingOnly},
  }`,
    )
    .join(",");

  return `// ⚠️ This file is auto-generated by integrations/routeGenerator.ts — do not edit manually. ⚠️

import { isPreview } from "@/config/stage";

export const removeTrailingSlash = (path: string) =>
  path.replace(/\\/$/, "").replace(/^$/, "/");

const buildUrl = (href: string): string => {
  const baseUrl = removeTrailingSlash(import.meta.env?.BASE_URL || "");
  return isPreview ? \`\${baseUrl}\${href}\` : href;
};

export const routes = {${entries},
} as const;
`;
}
