// ⚠️ This file is auto-generated by integrations/routeGenerator.ts — do not edit manually. ⚠️

export type Route = {
  readonly key: string;
  readonly path: string;
  readonly title: string;
  readonly parent: Route | null;
  readonly sitemap: boolean;
  readonly isStagingOnly: boolean;
  readonly navOrder: number | null;
  readonly navLabel: string | null;
};

export const barrierefreiheit = {
  key: "barrierefreiheit",
  path: "/barrierefreiheit",
  title: "Barrierefreiheit",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const begleitungen = {
  key: "begleitungen",
  path: "/begleitungen",
  title: "Regelungsbegleitung",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const datenschutz = {
  key: "datenschutz",
  path: "/datenschutz",
  title: "Datenschutzerklärung",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const home = {
  key: "home",
  path: "/",
  title: "Zentrum für Legistik",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const impressum = {
  key: "impressum",
  path: "/impressum",
  title: "Impressum",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const kontakt = {
  key: "kontakt",
  path: "/kontakt",
  title: "Kontakt",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const schulungen = {
  key: "schulungen",
  path: "/schulungen",
  title: "Schulungen",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const sitemap = {
  key: "sitemap",
  path: "/sitemap",
  title: "Sitemap",
  parent: null,
  sitemap: false,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const staging = {
  key: "staging",
  path: "/staging",
  title: "Staging-Umgebung",
  parent: null,
  sitemap: false,
  isStagingOnly: true,
  navOrder: null,
  navLabel: null,
} as const;

export const ueber = {
  key: "ueber",
  path: "/ueber",
  title: "Über uns",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const ueber_aktuelleMeldungen = {
  key: "ueber_aktuelleMeldungen",
  path: "/ueber/aktuelle-meldungen",
  title: "Aktuelle Meldungen",
  parent: ueber,
  sitemap: true,
  isStagingOnly: false,
  navOrder: 3,
  navLabel: null,
} as const;

export const ueber_dasIstNeu = {
  key: "ueber_dasIstNeu",
  path: "/ueber/das-ist-neu",
  title: "Das ist neu",
  parent: ueber,
  sitemap: true,
  isStagingOnly: false,
  navOrder: 1,
  navLabel: null,
} as const;

export const ueber_zahlenUndFakten = {
  key: "ueber_zahlenUndFakten",
  path: "/ueber/zahlen-und-fakten",
  title: "Zahlen und Fakten",
  parent: ueber,
  sitemap: true,
  isStagingOnly: false,
  navOrder: 2,
  navLabel: null,
} as const;

export const werkzeuge = {
  key: "werkzeuge",
  path: "/werkzeuge",
  title: "Werkzeuge",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const werkzeugfinder = {
  key: "werkzeugfinder",
  path: "/werkzeugfinder",
  title: "Werkzeugfinder für Visualisierungen",
  parent: null,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const werkzeugfinder_entscheidungsbaum = {
  key: "werkzeugfinder_entscheidungsbaum",
  path: "/werkzeugfinder/entscheidungsbaum",
  title: "Entscheidungsbaum Anleitung",
  parent: werkzeugfinder,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const werkzeugfinder_flussdiagramm = {
  key: "werkzeugfinder_flussdiagramm",
  path: "/werkzeugfinder/flussdiagramm",
  title: "Flussdiagramm Anleitung",
  parent: werkzeugfinder,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const werkzeugfinder_schaubild = {
  key: "werkzeugfinder_schaubild",
  path: "/werkzeugfinder/schaubild",
  title: "Schaubild Anleitung",
  parent: werkzeugfinder,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const werkzeugfinder_uebersicht = {
  key: "werkzeugfinder_uebersicht",
  path: "/werkzeugfinder/uebersicht",
  title: "Werkzeugübersicht",
  parent: werkzeugfinder,
  sitemap: true,
  isStagingOnly: false,
  navOrder: null,
  navLabel: null,
} as const;

export const allRoutes = [
  barrierefreiheit,
  begleitungen,
  datenschutz,
  home,
  impressum,
  kontakt,
  schulungen,
  sitemap,
  staging,
  ueber,
  ueber_aktuelleMeldungen,
  ueber_dasIstNeu,
  ueber_zahlenUndFakten,
  werkzeuge,
  werkzeugfinder,
  werkzeugfinder_entscheidungsbaum,
  werkzeugfinder_flussdiagramm,
  werkzeugfinder_schaubild,
  werkzeugfinder_uebersicht,
] as const;
