// ⚠️ This file is auto-generated by integrations/routeGenerator.ts — do not edit manually. ⚠️

import { isPreview } from "@/config/stage";

export const removeTrailingSlash = (path: string) =>
  path.replace(/\/$/, "").replace(/^$/, "/");

const buildUrl = (href: string): string => {
  const baseUrl = removeTrailingSlash(import.meta.env?.BASE_URL || "");
  return isPreview ? `${baseUrl}${href}` : href;
};

export const routes = {
  home: {
    path: buildUrl("/"),
    title: "Zentrum für Legistik",
    sitemap: true,
    order: 1,
    showInHeader: false,
    isStagingOnly: false,
  },
  anleitungenUndHilfsmittel: {
    path: buildUrl("/anleitungen-und-hilfsmittel"),
    title: "Anleitungen und Hilfsmittel",
    sitemap: true,
    order: 999,
    showInHeader: true,
    isStagingOnly: false,
  },
  barrierefreiheit: {
    path: buildUrl("/barrierefreiheit"),
    title: "Barrierefreiheit",
    sitemap: true,
    order: 999,
    showInHeader: false,
    isStagingOnly: false,
  },
  ueberUns_daranArbeitenWir: {
    path: buildUrl("/ueber-uns/daran-arbeiten-wir"),
    title: "Daran arbeiten wir",
    sitemap: true,
    order: 999,
    showInHeader: false,
    isStagingOnly: false,
  },
  datenschutz: {
    path: buildUrl("/datenschutz"),
    title: "Datenschutzerklärung",
    sitemap: true,
    order: 999,
    showInHeader: false,
    isStagingOnly: false,
  },
  impressum: {
    path: buildUrl("/impressum"),
    title: "Impressum",
    sitemap: true,
    order: 999,
    showInHeader: false,
    isStagingOnly: false,
  },
  begleitungen: {
    path: buildUrl("/begleitungen"),
    title: "Regelungsbegleitung",
    sitemap: true,
    order: 999,
    showInHeader: true,
    isStagingOnly: false,
  },
  schulungen: {
    path: buildUrl("/schulungen"),
    title: "Schulungen",
    sitemap: true,
    order: 999,
    showInHeader: true,
    isStagingOnly: false,
  },
  sitemap: {
    path: buildUrl("/sitemap"),
    title: "Sitemap",
    sitemap: false,
    order: 999,
    showInHeader: false,
    isStagingOnly: false,
  },
  ueberUns: {
    path: buildUrl("/ueber-uns"),
    title: "Über das Zentrum für Legistik",
    sitemap: true,
    order: 999,
    showInHeader: true,
    isStagingOnly: true,
  },
  ueberUns_zahlenUndFakten: {
    path: buildUrl("/ueber-uns/zahlen-und-fakten"),
    title: "Zahlen und Fakten",
    sitemap: true,
    order: 999,
    showInHeader: false,
    isStagingOnly: false,
  },
} as const;
