name: Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1" # every Monday at 10 am

jobs:
  link-checker:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Link Checker
        uses: digitalservicebund/link-checker-gha@b6a6f425ebb14549e6689b006d248bfcf6625412 # v2.1.1
        with:
          SITEMAP_URL: "https://zfl.bund.de/sitemap-0.xml"
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
