name: Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 1" # every Monday at 10 am

jobs:
  link-checker:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Link Checker
        uses: digitalservicebund/link-checker-gha@0b9677477e298cf3d8228ab1be8a10f1488860c6 # v2.0.1
        with:
          SITEMAP_URL: "https://zfl.bund.de/sitemap-0.xml"
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
